---
output_paths:
  linux   : dist/linux/sql-runner
  darwin  : dist/darwin/sql-runner
  windows : dist/windows/sql-runner

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "snowplow-generic"
    name     : "sql-runner"
    user_org : "snowplow"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= CMD['cat VERSION'] %>
    build_version : <%= ENV['TRAVIS_TAG'] %>

    build_commands:
      - gox -osarch=linux/amd64 -output={{ output_paths.linux }}
      - gox -osarch=darwin/amd64 -output={{ output_paths.darwin }}
      - gox -osarch=windows/amd64 -output={{ output_paths.windows }}

    artifacts:
      - prefix : "sql_runner_"
        suffix : "_linux_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.linux }}"
      - prefix : "sql_runner_"
        suffix : "_darwin_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.darwin }}"
      - prefix : "sql_runner_"
        suffix : "_windows_amd64"
        type   : "zip"
        binary_paths:
          - "{{ output_paths.windows }}.exe"
