language: go
go:
- 1.4
install:
- export PATH=$PATH:$HOME/gopath/bin
- go get -v -u github.com/kr/godep
- godep get
- godep go build -v ./...
before_script:
- ./integration/setup_travis.sh
script:
- godep go test -i ./...
- godep go test ./...
- test -z "$(go fmt ./...)"
- godep go build -v
- ./integration/run_tests.sh
addons:
  postgresql: '9.3'
env:
  global:
  - secure: eP2CEhjE6YEgajudRcW6Lsyy92IxAB1KS5Cw0p/defwpouSuZS4NF8+YjcUhfI9sbkobL6KGaL12CYqLWToepQpiDHJ1eRaH+/8HQ+kgqwLxmHptVlqEXhkQPVJL04MvxZqeXocuOluGlWHOHMdlmDTA7eI/tKJtyykIRKyXFAc=
  - secure: TP/mMjN910q8M/tknHkPxdYfKl25eQqdSscfTlQlnBxJpQgrgX25WgK1XuNI+IUTTmn1cM/eVRyKvUWflxqzwSUhgWO7s1EcN18WYU7Xl+RkWaoOMjqzV3q5l4M8rDK8LiBM/xrcz/rQMTZnWYm/tJ6+tjTQiuAezZh3bwuMvAo=
