language: go
go:
  - 1.4

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -u github.com/kr/godep
  - godep get
  - godep go build -v ./...

before_script:
  - ./integration/setup_travis.sh

script:
  - godep go test -i ./...
  - godep go test ./...
  - test -z "$(go fmt ./...)"
  - godep go build -v
  - ./integration/run_tests.sh

addons:
  postgresql: "9.3"
